version: '3.8'

services:
  # GROBID - Extração de texto completo de PDFs acadêmicos
  grobid:
    image: lfoppiano/grobid:0.8.0
    container_name: grobid-service
    ports:
      - "8070:8070"
    environment:
      - GROBID_OPTS=-Xmx4G
    volumes:
      - grobid-data:/opt/grobid/grobid-home/tmp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8070/api/isalive"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Redis - Cache para resultados de extração
  redis:
    image: redis:7-alpine
    container_name: resea-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru

  # Qdrant - Vector Database para busca semântica
  qdrant:
    image: qdrant/qdrant:latest
    container_name: resea-qdrant
    ports:
      - "6333:6333"  # HTTP API
      - "6334:6334"  # gRPC API
    volumes:
      - qdrant-data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Ollama - LLM local para embeddings e reranking
  ollama:
    image: ollama/ollama:latest
    container_name: resea-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  grobid-data:
  redis-data:
  qdrant-data:
  ollama-data:
